name: CI Downstream - MQTT Streaming

on:
  workflow_dispatch:
    inputs:
      opendaq-ref:
        description: "openDAQ SDK commit, branch or tag"
        required: false
        default: ""
  pull_request:

jobs:
  call-opendaq-reusable:
    name: MQTT Streaming
    uses: openDAQ/openDAQ-CI/.github/workflows/reusable.yml@jira/TBBAS-3031-reusable-ci
    with:
      opendaq-ref: ${{ github.event.inputs.opendaq-ref || '' }}
      packages: >
        [
          {
            "match-jobs": ["ubuntu-*"],
            "apt-install": ["mosquitto"],
            "run": "mosquitto -d"
          },
          {
            "match-jobs": ["windows-*"],
            "run": "winget install --id EclipseFoundation.Mosquitto --accept-source-agreements --accept-package-agreements"
          }
        ]
      cmake-presets: >
        [
          {
            "configure-preset": "module",
            "test-preset": "module-test"
          },
          {
            "match-jobs": ["macos-*"],
            "test-preset": ""
          }
        ]
