name: CI Downstream - MQTT Streaming

on:
  workflow_dispatch:
    inputs:
      opendaq-ref:
        description: "openDAQ SDK commit, branch or tag"
        required: false
        default: ""
  pull_request:

jobs:
  call-opendaq-reusable:
    name: MQTT Streaming
    uses: openDAQ/openDAQ-CI/.github/workflows/reusable.yml@v3
    with:
      opendaq-ref: ${{ github.event.inputs.opendaq-ref || '' }}
      include-jobs: >
        [
            "windows-2022-x86-msvs-v143-release",
            "windows-2022-x86_64-msvs-v143-debug",
            "ubuntu-20.04-x86-ninja-gcc-7-release",
            "ubuntu-20.04-x86_64-ninja-clang-9-release",
            "ubuntu-24.04-x86_64-ninja-gcc-14-debug",
            "ubuntu-24.04-x86_64-ninja-gcc-14-release",
            "ubuntu-24.04-x86_64-ninja-clang-18-release",
            "macos-26-x86_64-ninja-appleclang-17-release",
            "macos-26-x86_64-ninja-appleclang-17-debug",
            "macos-26-armv8-ninja-appleclang-21-release"
        ]
      packages: >
        [
          {
            "match-jobs": ["ubuntu-*"],
            "apt-install": ["mosquitto"],
            "run": "mosquitto -d"
          },
          {
            "match-jobs": ["windows-*"],
            "run": "$ErrorActionPreference='Stop'; Invoke-WebRequest -Uri 'https://mosquitto.org/files/binary/win64/mosquitto-2.0.18-install-windows-x64.exe' -OutFile mosq.exe; Start-Process -FilePath ./mosq.exe -ArgumentList '/S' -Wait; Start-Service mosquitto"
          },
          {
            "match-jobs": ["macos-*"],
            "brew-install": ["mosquitto"],
            "run": "$(brew --prefix mosquitto)/sbin/mosquitto -d"
          }
        ]
      cmake-presets: >
        [
          {
            "match-jobs": ["*"],
            "configure-preset": "module",
            "test-preset": "module-test"
          }
        ]
